define({
  "defaultAreaUnit": "Unidad de área predeterminada",
  "defaultLengthUnit": "Unidad de longitud predeterminada",
  "acres": "Acres",
  "sqMiles": "Millas cuadradas",
  "sqKilometers": "Kilómetros cuadrados",
  "hectares": "Hectáreas",
  "sqYards": "Yardas cuadradas",
  "sqFeet": "Pies cuadrados",
  "sqFeetUS": "Pies cuadrados (EE. UU.)",
  "sqMeters": "Metros cuadrados",
  "miles": "Millas",
  "kilometers": "Kilómetros",
  "feet": "Pies",
  "feetUS": "Pies (EE. UU.)",
  "meters": "Metros",
  "yards": "Yardas",
  "nauticalMiles": "Millas náuticas",
  "showArea": "Área",
  "showDistance": "Distancia",
  "showLocation": "Ubicación",
  "showtools": "Mostrar herramientas de medición:",
  "allHidedTips": "Se debe seleccionar al menos una herramienta.",
  "eneableAlt": "Habilitar medición altimétrica",
  "urlSubtitle": "URL's de servicios",
  "gsvcUrl": "Geometry server:",
  "tsvcUrl": "Transformations server:",
  "ug": "Cuenca:",
  "mapSys": "Id del sistema (mapa):",
  "DEMUrl": "Modelo de elevación digital:",
  "DEMAttr": "Atributo altitud:"
});