define({
	taskGeoUrl: "URL Geometry Service:",
    taskUrl:  "URL Perfíl Topográfico:",
    serviceURLPlaceholder: "Por favor ingrese la URL del Perfíl Topográfico",
    ok: "OK",
    cancel: "Cancelar",
    setTask: "Establecer",
    setTaskTitle: "Establecer la Tarea del Perfíl",
    invalidURL: "URL Inválida del Perfíl Topográfico",
    urlContainsProfile: "La URL de la Tarea no debe contener el sufijo: /Profile",
    feet: "Pies",
    metric: "Métrico",
    measureunits: "Unidad de Medida",
    chart: {
      title: "Perfíl de Elevación",
      elevationTitleTemplate: "Elevación en {0}",
      distanceTitleTemplate: "Distancia en {0}",
      chartTitleFontSize: "Tamaño de Fuente del Título del Gráfico",
      axisTitleFontSize: "Tamaño de Fuente del título de los Ejes",
      axisLabelFontSize: "Tamaño de Fuente de las etiquetas (valores) de los Ejes",
      indicatorFontColor: "Color de Fuente del Indicador",
      indicatorFillColor: "Color de Relleno del Indicador",
      titleFontColor: "Color de Fuente del Título del Gráfico",
      axisFontColor: "Color de Fuente de los Ejes",
      axisMajorTickColor: "Color de tick de los Ejes",
      skyTopColor: "Color del Cielo",
      skyBottomColor: "Color del Fondo",
      waterLineColor: "Color de la Línea del Agua",
      waterTopColor: "Color de la parte superior del Agua",
      waterBottomColor: "Color de la parte inferior del Agua",
      elevationLineColor: "Color de la Línea de Elevación",
      elevationTopColor: "Color de la Elavación",
      elevationBottomColor: "Color del Fondo",
      constrain: "Reestricción de la altura del perfíl a  320px",
      constraintooltip: "Use esta opción para establecer el Widget en un panel y no como un OnScreen Widget.",
    },
    editDefaultSym: "Editar el símbolo de la línea por defecto",
    editChartProperties: "Editar las propiedades visuales del Gráfico",
    lineSymbol: "Símbolo de Línea: ",
    symbologyTooltip: "Click sobre la simbología que desea editar.",
	setting_samples_title: "Máxima cantidad de muestras:",
	setting_initial_step_title: "Valor inicial del paso (metros):",
});
